### ISSUE TITLE
Errore impossibile accedere al file

### ISSUE THREAD

**Issue by gbfactory** [vvettoretti/hubscuola-downloader#1]
Eseguendo lo script ho il seguente errore in console:

```
Traceback (most recent call last):
  File "C:\Users\gbfactory\Desktop\hubscuola-downloader-main\main.py", line 21, in <module>
    h.download_book(str(book["id"]), book["title"] + ".pdf")
  File "C:\Users\gbfactory\Desktop\hubscuola-downloader-main\hubyoung_lib.py", line 61, in download_book
    shutil.rmtree("./publication")
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3312.0_x64__qbz5n2kfra8p0\lib\shutil.py", line 757, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3312.0_x64__qbz5n2kfra8p0\lib\shutil.py", line 627, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3312.0_x64__qbz5n2kfra8p0\lib\shutil.py", line 625, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] Impossibile accedere al file. Il file è utilizzato da un altro processo: './publication\\publication.db'
```

**Comment by vvettoretti** [comment]
Ciao, non ho mai incontrato questo errore, prova ad aggiungere a riga 60 dopo il select `db.close()` 
Se non funziona rimuovi il codice a riga 61 e rimuovi manualmente il file `publication.db` dopo aver scaricato il libro.
Se funziona fai un pr

**Comment by gbfactory** [comment]
Il db.close() funziona e sembra aver risolto, grazie mille!
